# fly.toml app configuration file generated for lumance on 2025-06-25T08:37:10+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lumance'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
